export const postData = [
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/09a2f1845c3959250bb3ffb16b9c6919673a1314.jpg',
    title:'Comprehensive Full Service',
    name:'Valley Tyres',
    description:'Wairau Valley',
    details:'Comprehensive Car Full Service Check incl. Diagnostic Scan, Comprehensive Oil & Filter Change',
    price:'$89',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/2ad1e4da576db483ba9c0257231fe497e20f8842.jpg',
    title:'Classic Eyelash Extension Session',
    name:'Venice Beauty',
    description:'Auckland Central',
    details:'Grab a classic eyelash extension session for $45 from Venice Beauty.',
    price:'$45',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/157c5337d933f885c87a3fa099744b9e05a1a8ac.jpg',
    title:'Grab a service for a Japanese car from Mairangi Automotive.',
    name:'Mairangi Automotive',
    description:'Rosedale',
    details:'Comprehensive Service for Japanese Car incl. Oil & Filter Change, Engine Flush & More - Option to incl. W.O.F.',
    price:'$99',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/322243058bc77aef87b7219b6dd77de76f68cc3c.jpg',
    title:'Grab Chinese therapy at Simply Soothing Massage Therapy.',
    name:'Simply Soothing Massage Therapy Mt Eden',
    description:'Mount Eden',
    details:'60-minute Full Body Chinese Oil Massage - Options for Couple, 90-Minute Massage with Chinese Medicine Doctor, or $40 Voucher for Chinese Medicine',
    price:'$55',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/91482e373dc1de3fb1d87d4764263a69a47549dc.jpg',
    title:'Grab a walk way pass from West Coast Treetop Walk and Cafe.',
    name:'West Coast Treetop Walk & Cafe',
    description:'South Island',
    details:'Adult Pass to The West Coast Treetop Walk Way - Option for Child Pass Available',
    price:'$19.20',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/33557a608ddec050e1c8989fb274082d205c549d.jpg',
    title:'Grab a chiropractic consult including x-rays, posture assessments and adjustments from Chiro Office.',
    name:'Chiro Office',
    description:'Auckland Central',
    details:'Extensive Chiropractic Consultation incl. Full Spinal, Physical & Orthopedic Exams, X- Rays & Adjustment - Options for Three or Four Adjustments',
    price:'$19',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/15ed88ffc5426736ba446488eeb1f3420696ae66.jpg',
    title:'Grab a remedial Chinese massage package from Free Flow Acupuncture.',
    name:'Free Flow Acupuncture',
    description:'Epsom',
    details:'30-Minute Remedial Chinese Massage incl. 15-Minute Cupping Treatment - Options for 1-Hour Session & Acupuncture Treatment',
    price:'$30',
  },
  {
    image:'https://main-cdn.grabone.co.nz/goimage/fullsize/4f11d35733862123d1861b92cd0413949bde5e00.jpg',
    title:'Grab a keratin hair straightening treatment for one person at Nader Hair.',
    name:'Nader Hair',
    description:'Auckland Central',
    details:'Keratin Hair Straightening Treatment for One Person - Option to incl. Cut',
    price:'$119',
  },
]